### ISSUE TITLE
[FD] performance improvement ideas

### ISSUE THREAD

**Issue by pvdz** [the-grid/finitedomain#101]
- [x] Idea: [Address two major `indexOf` performance issues](https://github.com/the-grid/finitedomain/issues/106)
- [x] Idea: [Reduce GC pressure by representing domains more memory efficient](https://github.com/the-grid/finitedomain/issues/123)
- [ ] Idea: [implement cycle cutting](https://github.com/the-grid/finitedomain/issues/100)
- [ ] Idea: [Optimize markov legends/vectors](https://github.com/the-grid/finitedomain/issues/99)
- [x] Idea: [Don't add solved vars to the var-to-propagators hash](https://github.com/the-grid/finitedomain/issues/98)
- [ ] Idea: [Optimize operations on bools](https://github.com/the-grid/finitedomain/issues/97)
- [ ] Idea: [More optimizations at compile time](https://github.com/the-grid/finitedomain/issues/96)
- [ ] Idea: [variables whose constraints have been eliminated should not actively be solved](https://github.com/the-grid/finitedomain/issues/95)
- [ ] Idea: [Improve memory behavior of tracking changed vars during propagation](https://github.com/the-grid/finitedomain/issues/94)
- [ ] Idea: [Value distributor that aims to solve/reject a propagator](https://github.com/the-grid/finitedomain/issues/#93)
- [ ] Idea: [Postpone or eliminate isSolved checks during propagation](https://github.com/the-grid/finitedomain/issues/92)
- [ ] Idea: [Var distributor that is based on most constraints affected](https://github.com/the-grid/finitedomain/issues/91)
- [ ] Idea: [Introduce a conditional that can prune constraints/vars](https://github.com/the-grid/finitedomain/issues/90)
- [ ] Idea: [Precompute var distributions](https://github.com/the-grid/finitedomain/issues/89)
- [ ] Idea: [Precompute value distributions](https://github.com/the-grid/finitedomain/issues/88)
- [ ] Idea: [Boolean specific reifiers](https://github.com/the-grid/finitedomain/issues/103)
- [ ] Idea: [Pre-optimize `distinct` by pruning solved vars](https://github.com/the-grid/finitedomain/issues/104)
- [ ] Idea: [Try to implement asm.js](https://github.com/the-grid/finitedomain/issues/108)
- [ ] Idea: [Implement fd in webassembly](https://github.com/the-grid/finitedomain/issues/109)
- [ ] Idea: [Prune values from a domain that are not in a list distributor's list](https://github.com/the-grid/finitedomain/issues/115)
- [ ] Idea: [Prune useless reifiers](https://github.com/the-grid/finitedomain/issues/116)
- [ ] Idea: [Trie optimizations](https://github.com/the-grid/finitedomain/issues/121)
